#!/bin/bash
./sender.sh 'm1' 'l' 'v5'
./sender.sh 'm1' 'r' 'v5'
./sender.sh 'm2' 'l' 'v5'
./sender.sh 'm2' 'r' 'v5'
./sender.sh 'm3' 'l' 'v5'
./sender.sh 'm3' 'r' 'v5'
./sender.sh 'm4' 'l' 'v5'
./sender.sh 'm4' 'r' 'v5'
./sender.sh 'm6' 'l' 'v5'
./sender.sh 'm6' 'r' 'v5'
